import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const resp = await fetch("http://localhost:9999/topics");
    const data = await resp.json();
    // @ts-expect-error 아직 문법이 익숙하지 않아서;
    const tags = data.map((item) => {
        return (
            <li key={item.id}>
                <Link href={`/read/${item.id}`}>{item.title}</Link>
            </li>
        );
    });
    // const tags = [
    //     <li>
    //         <Link href="/read/1">html</Link>
    //     </li>,
    //     <li>
    //         <Link href="/read/2">css</Link>
    //     </li>,
    //     <li>
    //         <Link href="/read/3">js</Link>
    //     </li>,
    // ];
    return (
        <html lang="en">
            <body>
                <div>
                    <h1>
                        <Link href="/">Web</Link>
                    </h1>
                    <input type="text" placeholder="search" />
                    <ol>{tags}</ol>
                    {children}
                    <ul>
                        <li>
                            <Link href="/create">create</Link>
                        </li>
                        <li>
                            <Link href="/update/id">update</Link>
                        </li>
                        <li>
                            <button>Delete</button>
                        </li>
                    </ul>
                </div>
            </body>
        </html>
    );
}
