import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div>
                    <h1>
                        <a href="/">Web</a>
                    </h1>
                    <ol>
                        <li>
                            <a href="/read/1">html</a>
                        </li>
                        <li>
                            <a href="/read/2">css</a>
                        </li>
                        <li>
                            <a href="/read/3">js</a>
                        </li>
                    </ol>
                    {children}
                    <ul>
                        <li>
                            <a href="/create">create</a>
                        </li>
                        <li>
                            <a href="/update/id">update</a>
                        </li>
                        <li>
                            <button>Delete</button>
                        </li>
                    </ul>
                </div>
            </body>
        </html>
    );
}
