import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div>
                    <h1>
                        <Link href="/">Web</Link>
                    </h1>
                    <input type="text" placeholder="search" />
                    <ol>
                        <li>
                            <Link href="/read/1">html</Link>
                        </li>
                        <li>
                            <Link href="/read/2">css</Link>
                        </li>
                        <li>
                            <Link href="/read/3">js</Link>
                        </li>
                    </ol>
                    {children}
                    <ul>
                        <li>
                            <Link href="/create">create</Link>
                        </li>
                        <li>
                            <Link href="/update/id">update</Link>
                        </li>
                        <li>
                            <button>Delete</button>
                        </li>
                    </ul>
                </div>
            </body>
        </html>
    );
}
